In [ ]:
import pandas as pd

In [ ]:
team1 ={"Name":["Nour","Mostafa","Ahmed"],
        "Age":["20","27","25"],
        "Height":["170","165","177"],
        "Weight":["70","60","80"]
        }
df1= pd.DataFrame(team1)
df1[['Age', 'Height', 'Weight']] = df1[['Age', 'Height', 'Weight']].astype(int)
print(df1)

      Name  Age  Height  Weight
0     Nour   20     170      70
1  Mostafa   27     165      60
2    Ahmed   25     177      80

In [ ]:
team2 ={"Name":["Ali","Samy","Amr"],
        "Age":["28","29","25"],
        "Height":["170","165","177"],
        "Weight":["68","56","78"]
        }
df2= pd.DataFrame(team2)
df2[['Age', 'Height', 'Weight']] = df2[['Age', 'Height', 'Weight']].astype(int)
print(df2)

   Name  Age  Height  Weight
0   Ali   28     170      68
1  Samy   29     165      56
2   Amr   25     177      78

In [ ]:
df1[['Age', 'Height', 'Weight']].corr()

            Age    Height    Weight
Age     1.00000 -0.184050 -0.277350
Height -0.18405  1.000000  0.995402
Weight -0.27735  0.995402  1.000000

In [ ]:
df2[['Age', 'Height', 'Weight']].corr()

             Age    Height    Weight
Age     1.000000 -0.982917 -0.944911
Height -0.982917  1.000000  0.989014
Weight -0.944911  0.989014  1.000000

In [ ]:
df1[['Age', 'Height', 'Weight']].corrwith(df2[['Age', 'Height', 'Weight']])

Age       0.000000
Height    1.000000
Weight    0.998625
dtype: float64

**Recommendatoin movie system **

In [ ]:
import pandas as pd
Movies={
"Spiderman":[3.5,5,1,4],
"James bond":[2.0,3.5,4,5],
"Titanic":[5.0,3.5,1.0,2.0]
}
ratings=pd.DataFrame(Movies)
print(ratings)

   Spiderman  James bond  Titanic
0        3.5         2.0      5.0
1        5.0         3.5      3.5
2        1.0         4.0      1.0
3        4.0         5.0      2.0

In [ ]:

new_ratings=pd.Series([1.0,5.0,2.5,4.0])
recommendation=ratings.corrwith(new_ratings)
print(recommendation)

Spiderman     0.538672
James bond    0.638095
Titanic      -0.319728
dtype: float64

In [ ]:
recommendation = recommendation.sort_values(by='Correlation', ascending=False)
print(recommendation)

        index  Correlation
1  James bond     0.638095
0   Spiderman     0.538672
2     Titanic    -0.319728

In [ ]:
recommendation = pd.DataFrame(recommendation,columns=['Correlation']).reset_index()
print(recommendation)

        index  Correlation
0   Spiderman     0.538672
1  James bond     0.638095
2     Titanic    -0.319728