In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [3]:
data = pd.read_csv("/content/measurements.csv")
data.head()

,date,temp,atemp,humidity,windspeed,weather_condition,weekday,month,holiday,workingday,fuel_price,pollution_index,google_trends_bike,demand
0,2020-01-01,16.24,35.76,66.6,16.03,Cloudy,2,1,0,0,10.79,133.8,39.0,2041
1,2020-01-02,33.52,33.97,56.6,8.30,Fog,3,1,0,1,10.93,109.4,77.0,3850
2,2020-01-03,26.96,11.27,45.1,3.04,Cloudy,4,1,0,1,11.15,57.6,27.0,3063
3,2020-01-04,22.96,7.22,81.4,19.44,Rain,5,1,0,1,11.50,137.3,36.0,2708
4,2020-01-05,9.68,8.22,47.5,17.91,Clear,6,1,0,1,8.59,116.3,90.0,2158

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                366 non-null    object
 1   temp                366 non-null    float64
 2   atemp               366 non-null    float64
 3   humidity            366 non-null    float64
 4   windspeed           366 non-null    float64
 5   weather_condition   366 non-null    object
 6   weekday             366 non-null    int64
 7   month               366 non-null    int64
 8   holiday             366 non-null    int64
 9   workingday          366 non-null    int64
 10  fuel_price          366 non-null    float64
 11  pollution_index     366 non-null    float64
 12  google_trends_bike  366 non-null    float64
 13  demand              366 non-null    int64
dtypes: float64(7), int64(5), object(2)
memory usage: 40.2+ KB

In [ ]:
data['distance']=data['distance'].str.replace(',','.').astype(float)
data['consume']=data['consume'].str.replace(',','.').astype(float)
data['temp_inside']=data['temp_inside'].str.replace(',','.').astype(float)

In [ ]:
x = data[['distance','speed','temp_outside','gas_type','AC','rain','sun']]
y = data['consume']

In [ ]:
x= pd.get_dummies(x,columns=['gas_type'])

In [ ]:
x.head()

   distance  speed  temp_outside  AC  rain  sun  gas_type_E10  gas_type_SP98
0      28.0     26            12   0     0    0          True          False
1      12.0     30            13   0     0    0          True          False
2      11.2     38            15   0     0    0          True          False
3      12.9     36            14   0     0    0          True          False
4      18.5     46            15   0     0    0          True          False

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
coefficients = pd.DataFrame({'Feature': x.columns, 'Coefficient': model.coef_})
print(coefficients)

         Feature  Coefficient
0       distance     0.003290
1          speed    -0.020768
2   temp_outside    -0.040536
3             AC     0.427731
4           rain     0.610922
5            sun    -0.121871
6   gas_type_E10     0.019333
7  gas_type_SP98    -0.019333

In [ ]:
Y_pred =model.predict(X_test)

In [ ]:
pd.DataFrame({'Y_test': y_test, 'Y_Predicted': Y_pred})

     Y_test  Y_Predicted
271     5.6     4.729216
46      5.1     5.169342
167     6.1     5.076150
42      4.6     5.136480
349     4.3     4.527260
..      ...          ...
3       3.9     4.836909
18      4.9     5.060587
93      4.7     4.813368
108     4.7     5.199983
255     4.4     5.138808

[78 rows x 2 columns]

In [ ]:
mse = mean_squared_error(y_test, Y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.7673641296720836