In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [3]:
data = pd.read_csv("/content/boom_bike_demand_dataset.csv")
data.head()

,date,temp,atemp,humidity,windspeed,weather_condition,weekday,month,holiday,workingday,fuel_price,pollution_index,google_trends_bike,demand
0,2020-01-01,16.24,35.76,66.6,16.03,Cloudy,2,1,0,0,10.79,133.8,39.0,2041
1,2020-01-02,33.52,33.97,56.6,8.30,Fog,3,1,0,1,10.93,109.4,77.0,3850
2,2020-01-03,26.96,11.27,45.1,3.04,Cloudy,4,1,0,1,11.15,57.6,27.0,3063
3,2020-01-04,22.96,7.22,81.4,19.44,Rain,5,1,0,1,11.50,137.3,36.0,2708
4,2020-01-05,9.68,8.22,47.5,17.91,Clear,6,1,0,1,8.59,116.3,90.0,2158

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                366 non-null    object
 1   temp                366 non-null    float64
 2   atemp               366 non-null    float64
 3   humidity            366 non-null    float64
 4   windspeed           366 non-null    float64
 5   weather_condition   366 non-null    object
 6   weekday             366 non-null    int64
 7   month               366 non-null    int64
 8   holiday             366 non-null    int64
 9   workingday          366 non-null    int64
 10  fuel_price          366 non-null    float64
 11  pollution_index     366 non-null    float64
 12  google_trends_bike  366 non-null    float64
 13  demand              366 non-null    int64
dtypes: float64(7), int64(5), object(2)
memory usage: 40.2+ KB

In [6]:
X = data[['temp', 'humidity', 'windspeed', 'workingday', 'holiday',
        'fuel_price', 'pollution_index', 'google_trends_bike']]

y = data['demand']

In [8]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [9]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [11]:
coefficients = pd.DataFrame({'Feature': X.columns, 'Coefficient': model.coef_})
print(coefficients)

              Feature  Coefficient
0                temp    39.669034
1            humidity    -4.592047
2           windspeed    -7.463497
3          workingday   368.278032
4             holiday  -338.523609
5          fuel_price    -9.393201
6     pollution_index     0.377844
7  google_trends_bike    -0.123072

In [13]:
Y_pred =model.predict(X_test)
Y_pred

array([3215.30968184, 2965.73687399, 2047.20488518, 2820.63602245,
       2305.57342381, 2957.40606333, 3151.02723771, 2733.06899539,
       2238.71710027, 2888.72796965, 2390.64522937, 1973.14851769,
       3281.30681251, 2945.54094521, 2947.20202207, 2966.93937728,
       2211.34597602, 2689.78016377, 2706.45592694, 3166.15592904,
       3107.29751361, 3106.59923124, 2195.47623603, 2608.11197221,
       3429.97921486, 2608.95577688, 3196.553755  , 3127.08664271,
       2803.74972023, 2863.7801988 , 3076.9530248 , 2626.25245396,
       2141.61855938, 2052.25309073, 3007.94632607, 2777.60476038,
       2569.31215547, 2649.38151649, 1828.37187293, 2250.54261366,
       3137.5923746 , 2684.39033412, 2674.19640056, 3150.52536154,
       1910.85109522, 2430.30815015, 2465.43281885, 2356.17536686,
       1886.80917551, 2951.31407923, 2484.68374984, 2340.64617564,
       2235.57117584, 2380.34311812, 3109.14693906, 2863.61905456,
       2734.98200003, 2747.80959154, 2710.18850401, 2439.22451119,
       1893.30349033, 3511.58486483, 2436.57760566, 2561.03682843,
       2892.98357155, 2661.51036021, 2125.2244244 , 2625.43246574,
       3306.62428864, 2400.7632387 , 3192.1894472 , 3317.85257583,
       2347.7664928 , 2522.45157728])

In [16]:
pd.DataFrame({'Y_test': y_test, 'Y_Predicted': Y_pred})

     Y_test  Y_Predicted
193    3096  3215.309682
33     2846  2965.736874
15     2256  2047.204885
310    2745  2820.636022
57     2282  2305.573424
..      ...          ...
82     2397  2400.763239
94     2923  3192.189447
192    3341  3317.852576
307    2456  2347.766493
211    2611  2522.451577

[74 rows x 2 columns]

In [17]:
mse = mean_squared_error(y_test, Y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 24779.95421209133

In [18]:
mse = mean_squared_error(y_test, Y_pred)
print("Mean Squared Error:", mse)
print("Model Score (R²):", model.score(X_test, y_test))

Mean Squared Error: 24779.95421209133
Model Score (R²): 0.8771010293042553